FROM node:22-alpine

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app

COPY package.json .
COPY pnpm-workspace.yaml .
COPY turbo.json .

COPY apps/web/package.json ./apps/web/

RUN pnpm install

COPY . .

EXPOSE 3000

CMD ["pnpm", "dev"]